# Generated by Django 5.1 on 2024-09-21 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='customer',
            name='current_plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.package'),
            preserve_default=False,
        ),
    ]
