# Generated by Django 5.1 on 2024-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_status_order_is_confirmed_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
