# Generated by Django 5.1 on 2024-09-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_package_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
