# Generated by Django 5.1 on 2024-09-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(default=None, editable=False, max_length=250, unique=True),
        ),
    ]
