# Generated by Django 5.1 on 2024-09-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_order_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.package'),
        ),
    ]
