# Generated by Django 5.1 on 2024-09-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_customer_email_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
