# Generated by Django 5.1 on 2024-09-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
