# Generated by Django 5.1 on 2024-09-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_date_alter_order_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
