# Generated by Django 5.1 on 2024-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_confirmed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expired_plan',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
