# Generated by Django 5.1 on 2024-09-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_expired_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mt5_id',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
