# Generated by Django 5.1 on 2024-09-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_mt5_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='line_user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
