# Generated by Django 5.1 on 2024-09-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture_url',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
