# Generated by Django 5.1 on 2024-10-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ctrader',
            field=models.CharField(blank=True, default=None, max_length=7, null=True),
        ),
    ]
